Login-Signup component completed
BuildForSDGCohort2/Team-038-Frontend pull request #27
Opened 2020-09-07 23:03 UTC by PopeFrancisOgbonna

![login-signup](https://user-images.githubusercontent.com/53881827/92419604-716abc00-f166-11ea-9689-a2707a5fa2b2.PNG)

I attached an image of the component so you can as well view.

2020-09-07 23:54 UTC, gidox1 submitted a review, later dismissed

2020-09-08 05:27 UTC, jidsfotech approved these changes, later dismissed

2020-09-08 18:58 UTC, AugustBemsen requested changes
Please Make the card white, use the color in the UI design. and your terms and policy should be black, and align them at the bottom right

2020-09-09 13:04 UTC, PopeFrancisOgbonna commented
> Please Make the card white, use the color in the UI design. and your terms and policy should be black, and align them at the bottom right

Implemented
![image](https://user-images.githubusercontent.com/53881827/92601925-52267880-f2a5-11ea-8e9c-ca6b94b5c095.png)

2020-09-10 06:58 UTC, jidsfotech approved these changes

2020-09-10 12:07 UTC, AugustBemsen approved these changes

2020-09-13 20:24 UTC, gidox1 approved these changes

2020-09-13 20:24 UTC, merged